[project]
name = "clean-arch-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "acryl-datahub[datahub-rest]>=1.4.0.9",
    "dbt-snowflake>=1.9.4,<1.10.0",
    "duckdb>=1.5.0",
    "faker>=40.11.0",
    "polars>=1.0.0",
    "snowflake-connector-python>=3.13.1,<4.0.0",
]
